# Generated by Django 2.2 on 2019-04-11 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('index_order', models.IntegerField(default=999)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('content', models.TextField(max_length=60000)),
                ('author', models.CharField(max_length=50)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('visit_time', models.PositiveIntegerField(default=0)),
                ('article_image', models.ImageField(max_length=3000, upload_to='%Y%m%d')),
                ('article_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myBlog.Category')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
